### ISSUE TITLE
What is the difference between accelerometer.txt and accelerometer#1.txt?

### ISSUE THREAD

**Issue by VellalaVineethKumar** [tyrex-team/senslogs#2]

**Comment by ThibaudM** [comment]
It seems that you have 2 instances of "TYPE_ACCELEROMETER" on your device.

**Comment by VellalaVineethKumar** [comment]
so which one should I consider right?

**Comment by ThibaudM** [comment]
That is a good question.
With Android SDK, the common practice for a developer is to use of the method [SensorManager.getDefaultSensor](https://developer.android.com/reference/android/hardware/SensorManager#getDefaultSensor(int)). Here on this project, I retrieve the list of sensors available using [SensorManager.getSensorList](https://developer.android.com/reference/android/hardware/SensorManager#getSensorList(int)), you can see it here: https://github.com/tyrex-team/senslogs/blob/master/app/src/main/java/fr/inria/tyrex/senslogs/control/SensorsManager.java#L46

So, in Senslogs project you cannot know for sure if accelerometer.txt or accelerometer#1.txt is the default sensor considered by the manufacturer. I would tend to say that the first in the list (accelerometer.txt) is the default one.

**Comment by VellalaVineethKumar** [comment]
Ahhh got it. Thanks for the quick response!
