### ISSUE TITLE
[Camera] Focus parameter

### ISSUE THREAD

**Issue by anisghaoui** [tyrex-team/senslogs#8]
Hello,
I had a question about the Cemera sensor parameters one of them being `Auto-Focus`.
it is either Off or continuous.

When turned off, the video feed is blurry. Which I guess that the focal point is either too close or too far. Is there anyway for the app to lock the focus at a certain value? 

Thank you.

edit: as far as I see, there is a procedure described [here](https://stackoverflow.com/questions/42127464/how-to-lock-focus-in-camera2-api-android) but I lack the insight to full comprehend it.

**Comment by anisghaoui** [comment]
Hi as a side note, i have a very good alternative.  This [app](https://github.com/OSUPCVLab/mobile-ar-sensor-logger) allows to lock the focus and gives the intrinsic parameters after recording.
It is much simpler than SensLogs but solves my case.

Thibaud, you may want to take a look at it. You can close this issue if you believe that this is a feature request?

Thank you.

**Comment by ThibaudM** [comment]
I did not know this app before but seems to do exactly what you are looking for.
I do not have too much time to enhance SensLogs, so let's consider switching to this one ;)
